### ISSUE TITLE
Python tests are segfaulting on CentOS 8

### ISSUE THREAD

**Issue by ckreibich** [zeek/broker#199] opened 2021-08-26 19:05 UTC
Broker's CI has begun to fail on CentOS 8, but the problem isn't specific to Cirrus. It affects all of the Python tests, which fail as follows:

```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff392f5f7 in caf::uri::impl_type::impl_type (this=0x7ffff3c94880 <(anonymous namespace)::default_instance>) at /root/broker/caf/libcaf_core/src/uri.cpp:29
#2  0x00007ffff393496d in __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535) at /root/broker/caf/libcaf_core/src/uri.cpp:23
#3  0x00007ffff393499d in _GLOBAL__sub_I_uri.cpp(void) () at /root/broker/caf/libcaf_core/src/uri.cpp:203
#4  0x00007ffff7ddf8ba in call_init.part () from /lib64/ld-linux-x86-64.so.2
#5  0x00007ffff7ddf9ba in _dl_init () from /lib64/ld-linux-x86-64.so.2
#6  0x00007ffff677027c in _dl_catch_exception () from /lib64/libc.so.6
#7  0x00007ffff7de3e8e in dl_open_worker () from /lib64/ld-linux-x86-64.so.2
#8  0x00007ffff6770224 in _dl_catch_exception () from /lib64/libc.so.6
#9  0x00007ffff7de36b1 in _dl_open () from /lib64/ld-linux-x86-64.so.2
#10 0x00007ffff6f841ea in dlopen_doit () from /lib64/libdl.so.2
#11 0x00007ffff6770224 in _dl_catch_exception () from /lib64/libc.so.6
#12 0x00007ffff67702e3 in _dl_catch_error () from /lib64/libc.so.6
#13 0x00007ffff6f84969 in _dlerror_run () from /lib64/libdl.so.2
#14 0x00007ffff6f8428a in dlopen@@GLIBC_2.2.5 () from /lib64/libdl.so.2
#15 0x00007ffff7596aca in _PyImport_FindSharedFuncptr () from /lib64/libpython3.6m.so.1.0
#16 0x00007ffff75a69ca in _PyImport_LoadDynamicModuleWithSpec () from /lib64/libpython3.6m.so.1.0
#17 0x00007ffff75a6c11 in _imp_create_dynamic () from /lib64/libpython3.6m.so.1.0
#18 0x00007ffff753d202 in PyCFunction_Call () from /lib64/libpython3.6m.so.1.0
```

Here's a Dockerfile that currently drops you into the crash:

```
FROM centos:8

RUN yum update -y
RUN yum install -y cmake gcc gcc-c++ git make openssl-devel python3 python3-devel gdb
RUN git clone --rec https://github.com/zeek/broker
RUN cd broker && ./configure --enable-debug && make -j $(nproc)

ENV PYTHONPATH /broker/build/python
WORKDIR /broker/build/python

ENTRYPOINT gdb --eval-command run --args python3 ../../tests/python/communication.py
```

It's specific to CentOS 8 — I'm not seeing this on CentOS Stream or other distros.

**Comment by timwoj** [comment] 2022-02-04 16:52
Now that CentOS 8 has gone EOL and we no longer support it, can we just close this ticket?

**Comment by Neverlord** [comment] 2022-02-06 12:23
If we can't reproduce this anywhere else, I'd say yes.

**Closed** 2022-02-07 17:44 UTC
